// Generated by CoffeeScript 1.4.0
var BufferedStream, stream, util;

stream = require('stream');

util = require('util');

BufferedStream = function(size) {
  if (size == null) {
    size = 1024 * 1024;
  }
  this.writable = true;
  this.readable = true;
  this.size = size;
  this.buffer = new Buffer(size);
  this.bufferPos = 0;
  return this;
};

BufferedStream.prototype.__proto__ = stream.prototype;

BufferedStream.prototype.write = function(data) {
  var dataLength, dataWritten;
  if (Buffer.isBuffer(data)) {
    data = data.toString();
  }
  dataLength = Buffer.byteLength(data, 'utf8');
  dataWritten = this.buffer.write(data, this.bufferPos);
  this.bufferPos += dataWritten;
  if (dataWritten !== dataLength) {
    this.emit('data', this.buffer.slice(0, this.bufferPos).toString());
    (new Buffer(data)).copy(this.buffer, 0, dataWritten, dataLength);
    this.bufferPos = dataLength - dataWritten;
  }
  return this.paused;
};

BufferedStream.prototype.pause = function(data) {
  return this.paused = true;
};

BufferedStream.prototype.resume = function(data) {
  this.paused = false;
  return this.emit('drain');
};

BufferedStream.prototype.end = function() {
  this.emit('data', this.buffer.slice(0, this.bufferPos));
  this.writable = false;
  this.readable = false;
  return this.emit('end');
};

module.exports = BufferedStream;
